package au.edu.swin.sdmd.rotations;

import android.arch.lifecycle.LiveData;

import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.Query;

import java.util.List;

/**
 * Room has three components: database, entity and DAO. This is a DAO file which is your access
 * to the database, both read and write. Note it is an interface as the actual object will
 * autogenerated.
 */

@Dao
public interface PersonDao {
    @Query("SELECT * FROM person ORDER BY name")
    List<Person> getAll();

    @Insert
    void insert(Person person);

    @Delete
    void delete(Person person);

    @Query("DELETE FROM person")
    void deleteAll();

    @Query("SELECT COUNT(*) FROM person")
    int count();
}
